### ISSUE TITLE
Site-wide Link Design Update (Aug-2020)

### ISSUE THREAD

**Issue by nelsonni** [EPICLab/EPICLab.github.io#27]
The default web design standard for links is that they be shown as blue text, which becomes a darker blue and underlined on hover (to suggest that mouse actions such as clicking are possible on that text). The Nielsen Norman Group (of [Nielsen's 10 Usability Heuristics](https://www.nngroup.com/articles/ten-usability-heuristics/) fame) has a good article, [_"Guidelines for Visualizing Links"_](https://www.nngroup.com/articles/guidelines-for-visualizing-links/), that discusses design best practices for links.

There are currently several different link visualization designs being used throughout the `EPICLab.github.io` site, including:

- **Button links** that change text color when the mouse is hovered.
    <img src="https://user-images.githubusercontent.com/6432572/90282806-dced9200-de23-11ea-9e8d-fb67af5c0a82.png" width="300">

- **External links** that adhere to the default blue text that changes color and underlined on hover.
<img src="https://user-images.githubusercontent.com/6432572/90283175-8a60a580-de24-11ea-807c-05d374596808.png" width="600">

- **Document links** that do not indicate clickability until you hover, at which point a link icon appears.
<img src="https://user-images.githubusercontent.com/6432572/90283222-a6644700-de24-11ea-8a6f-cb10f8d2b393.png" width="600">

We need to develop a unified standard for how we visually communicate links throughout the website. This issue is an expansion of some discussion found in #26.

**Comment by audreyau** [comment]
Do we plan to add individual pages for all the news articles? If not, I will take away the links...
![Screen Shot 2020-08-14 at 12 19 24 PM](https://user-images.githubusercontent.com/52758047/90285282-7028c680-de28-11ea-9a11-93f7943a7a67.png)

so that it looks less misleading. However, the normal font for the news heading makes it seem trivial so...
![Screen Shot 2020-08-14 at 12 19 00 PM](https://user-images.githubusercontent.com/52758047/90285291-7323b700-de28-11ea-8562-acd1d05ecdb7.png)

I think we should make them bold.
![Screen Shot 2020-08-14 at 12 19 12 PM](https://user-images.githubusercontent.com/52758047/90285289-728b2080-de28-11ea-900a-715952712d26.png)

Haha I understand the article you sent now. It's confusing to know what is a link when the EPICLab site has inconsistent link formatting. I think having links in blue would be the most obvious to users, but it makes the site seem too conventional. They would also make the [Publications Page](https://epiclab.github.io/publications.html) very hard to read due to the abundance of links.

I looked at the [STRUDEL Lab's website](https://cmustrudel.github.io/projects/sustainability/), and they made their links in red. When a user hovers over a link, the red color becomes slightly more saturated. I like how that design goes along with their website aesthetics and how it doesn't involve bold text, which can then be used for key points and big ideas.

[Amy X. Zhang's website](https://homes.cs.washington.edu/~axz/) has the links in bold. For her website design, it works well, and when a user hovers over the links, they turn a bright yellow, indicating an obvious link. However, since the publication titles are in bold, I thought they'd have links too, which they didn't. So bold links might be misleading. 

For our [People Page](https://epiclab.github.io/people.html), the links are quite confusing since all the people have their names in bold, but only certain names have links. However, if we were to make the names with links in different colors, I think that would be even worse since the design would be very inconsistent. 

Underlined links are nice, but they might be too messy. Should we just do a mix of all of them?

**Comment by nelsonni** [comment]
I would like to have a single design for all links (which are defined by `<a href="">` tags in HTML), such that we can defined this design in CSS in similar fashion to this:
```css
a:link {
  color: #547599;
  text-decoration: none;
  cursor: auto;
}

a:hover {
  color: #547599;
  text-decoration: underline;
}

a:visited {
  color: inherit;
  text-decoration: underline;
}
``` 
As reference, the [CSS Default Values Reference](https://www.w3schools.com/cssref/css_default_values.asp). Although that W3School site doesn't include actual values for those CSS defaults, it does indicate which fields are set. And at least in Firefox, the default link color is #0056b3 (I updated my example above to a color that is closer to the color palette of the rest of the EPICLab website).

**Comment by audreyau** [comment]
I've removed the link icon that pops up for publications/people and created the CSS code, but for some reason, the links don't change color. They remain black. Also, later on, should we label the publications that have won awards?

**Comment by nelsonni** [comment]
It would be easier to diagnose the indicated problem if you commit your changes to the `changes` branch and push it up to GitHub, because I could pull your code down and directly examine it. There are two changes that need to happen for removing the `popup` icons that appear on hover next to a link:

1. Remove the following CSS rules from [`full-width-pics.css`](https://github.com/EPICLab/EPICLab.github.io/blob/changes/css/full-width-pics.css):
   ```css
   .name-box .site-link #popup {
     font-weight: bold;
     font-size: 18px;
     color:white;
   }

   .name-box .site-link:hover #popup {
     font-weight: bold;
     font-size: 18px;
     color: black;
   }

   .name-box .site-link:hover {
     color: black;
     font-weight: bold;
     font-size: 1rem;  
     line-height: 1.5;
   }
   ```

2. Remove all instances of the following from both [`publications.html`](https://github.com/EPICLab/EPICLab.github.io/blob/changes/publications.html) and [`people.html`](https://github.com/EPICLab/EPICLab.github.io/blob/changes/people.html):
   ```html
   <i class="fas fa-link" ID="popup"></i>
   ```

The property that is directly setting the link text to be black is `color` rule on [`full-width-pics.css#L452`](https://github.com/EPICLab/EPICLab.github.io/blob/changes/css/full-width-pics.css#L452):
```css
   .site-link {
     font-size: 1rem; 
     font-weight: bold; 
     line-height: 1.5;
     color: black;
   }
```

I think adding something to signify awards would be appropriate, but not as part of this issue. If you want to suggest it in a new issue, we can discuss how to design such a feature.

**Comment by audreyau** [comment]
I've committed my changes and tried to do all the changes you sent, but the links still remain black. Do I need to make a separate class for them?

**Comment by nelsonni** [comment]
I looked into the code and figured out the problem. The following CSS rule in [`full-width-pics.css`](https://github.com/EPICLab/EPICLab.github.io/blob/d22c4c6a03ba095e2f92f2150e042e85485bbd25/css/full-width-pics.css) was supposed to allow the text color to be inherited from the `a:link` (`color: #547599;`), but was actually inheriting from `body` (`color: #212529;`):
   ```css
   a:visited {
      color: inherit;
      ...
   }
   ```
I pushed https://github.com/EPICLab/EPICLab.github.io/commit/d22c4c6a03ba095e2f92f2150e042e85485bbd25 to resolve the issue.
